[package]
name = "km003c-rs"
version = "0.1.0"
edition = "2024"

[dependencies]
byteorder = "1.5.0"
bytes = "1.10.1"
futures-lite = "2.6.0"
nusb = "0.1.14"
rtshark = "3.2.0"
tokio = { version = "1.45", features = ["full"] }
tracing = "0.1.41"
tracing-subscriber = "0.3.19"
