"""
KM003C Python bindings

This package provides Python bindings for parsing KM003C USB power meter data.
"""

from .km003c_lib import (
    # Data classes
    AdcData,
    SampleRate,
    AdcQueueSample,
    AdcQueueData,
    AdcQueueSampleRaw,
    AdcQueueRawData,
    PdStatus,
    PdEvent,
    PdEventStream,
    PdTrace,
    PdTraceStateEvent,
    PdTraceProtocolEvent,
    LogMetadata,
    LogicalPacket,
    # Parsing functions
    parse_raw_adc_data,
    parse_packet,
    parse_packet_with_graph_rate,
    parse_raw_packet,
    get_sample_rates,
    create_packet,
    # Authenticated command helpers
    build_memory_read_packet,
    decrypt_memory_payload,
    parse_memory_read_confirmation,
    build_streaming_auth_packet,
    parse_streaming_auth_response,
    parse_log_metadata,
    parse_offline_log_samples,
    # USB constants
    VID,
    PID,
    INTERFACE_VENDOR,
    ENDPOINT_OUT_VENDOR,
    ENDPOINT_IN_VENDOR,
    INTERFACE_HID,
    ENDPOINT_OUT_HID,
    ENDPOINT_IN_HID,
    # Command types
    CMD_SYNC,
    CMD_CONNECT,
    CMD_DISCONNECT,
    CMD_ACCEPT,
    CMD_REJECT,
    CMD_GET_DATA,
    CMD_START_GRAPH,
    CMD_STOP_GRAPH,
    CMD_ENABLE_PD_MONITOR,
    CMD_DISABLE_PD_MONITOR,
    CMD_MEMORY_READ,
    CMD_STREAMING_AUTH,
    # Attribute constants
    ATT_ADC,
    ATT_ADC_QUEUE,
    ATT_ADC_QUEUE_10K,
    ATT_SETTINGS,
    ATT_PD_PACKET,
    ATT_PD_TRACE,
    ATT_LOG_METADATA,
    # Sample rates
    RATE_2_SPS,
    RATE_10_SPS,
    RATE_50_SPS,
    RATE_1000_SPS,
    # Device memory map
    ADDR_DEVICE_INFO,
    ADDR_FIRMWARE_INFO,
    ADDR_CALIBRATION,
    ADDR_PREFERRED_CALIBRATION,
    ADDR_HARDWARE_ID,
    ADDR_OFFLINE_LOG,
    INFO_BLOCK_SIZE,
    HARDWARE_ID_SIZE,
    LOG_METADATA_SIZE,
    OFFLINE_LOG_SAMPLE_SIZE,
    __version__,
)

__all__ = [
    # Data classes
    "AdcData",
    "SampleRate",
    "AdcQueueSample",
    "AdcQueueData",
    "AdcQueueSampleRaw",
    "AdcQueueRawData",
    "PdStatus",
    "PdEvent",
    "PdEventStream",
    "PdTrace",
    "PdTraceStateEvent",
    "PdTraceProtocolEvent",
    "LogMetadata",
    "LogicalPacket",
    # Parsing functions
    "parse_raw_adc_data",
    "parse_packet",
    "parse_packet_with_graph_rate",
    "parse_raw_packet",
    "get_sample_rates",
    "create_packet",
    # Authenticated command helpers
    "build_memory_read_packet",
    "decrypt_memory_payload",
    "parse_memory_read_confirmation",
    "build_streaming_auth_packet",
    "parse_streaming_auth_response",
    "parse_log_metadata",
    "parse_offline_log_samples",
    # USB constants
    "VID",
    "PID",
    "INTERFACE_VENDOR",
    "ENDPOINT_OUT_VENDOR",
    "ENDPOINT_IN_VENDOR",
    "INTERFACE_HID",
    "ENDPOINT_OUT_HID",
    "ENDPOINT_IN_HID",
    # Command types
    "CMD_SYNC",
    "CMD_CONNECT",
    "CMD_DISCONNECT",
    "CMD_ACCEPT",
    "CMD_REJECT",
    "CMD_GET_DATA",
    "CMD_START_GRAPH",
    "CMD_STOP_GRAPH",
    "CMD_ENABLE_PD_MONITOR",
    "CMD_DISABLE_PD_MONITOR",
    "CMD_MEMORY_READ",
    "CMD_STREAMING_AUTH",
    # Attribute constants
    "ATT_ADC",
    "ATT_ADC_QUEUE",
    "ATT_ADC_QUEUE_10K",
    "ATT_SETTINGS",
    "ATT_PD_PACKET",
    "ATT_PD_TRACE",
    "ATT_LOG_METADATA",
    # Sample rates
    "RATE_2_SPS",
    "RATE_10_SPS",
    "RATE_50_SPS",
    "RATE_1000_SPS",
    # Device memory map
    "ADDR_DEVICE_INFO",
    "ADDR_FIRMWARE_INFO",
    "ADDR_CALIBRATION",
    "ADDR_PREFERRED_CALIBRATION",
    "ADDR_HARDWARE_ID",
    "ADDR_OFFLINE_LOG",
    "INFO_BLOCK_SIZE",
    "HARDWARE_ID_SIZE",
    "LOG_METADATA_SIZE",
    "OFFLINE_LOG_SAMPLE_SIZE",
    "__version__",
]
