[package]
name = "km003c-lib"
version = "0.1.0"
edition = "2024"
authors = ["Danila Gornushko <me@okhsunrog.dev>"]
license = "MIT"
repository = "https://github.com/okhsunrog/km003c-rs"

[dependencies]
modular-bitfield = "0.12"
nusb = "0.1.14"
thiserror = "2.0.12"
tracing = "0.1.41"
tokio = { version = "1.45", features = ["full"] }
bytes = "1.10.1"
num_enum = "0.7.3"
zerocopy = { version = "0.8", features = ["derive"] }
strum_macros = "0.27.1"
usbpd = { version = "1.0.2", features = ["log"] }
uom = { version = "0.36.0", default-features = false, features = ["std", "si"] }

[dev-dependencies]
hex = "0.4"
rtshark = "3.2.0"
tracing-subscriber = { version = "0.3.19", features = ["registry", "env-filter"] }
clap = { version = "4.5", features = ["derive"] }
clap-verbosity-flag = { version = "3.0.3", default-features = false, features = ["tracing"] }
tracing-appender = "0.2.3"
rusqlite = { version = "0.36.0", features = [] }
